#!/bin/sh
# vim: fdl=2 ft=sh:

# $OSL/nodes/jo/export
#  $OSL  defined in
#   $MSn/WSL/bash_profile
#   $OSAB/nodes-Bash/export-storage

#  symlinked in  $OSAB/nodes-set/jo-0-Bash-X.sh, then sourced by  $AjB/bash_profile
#   also sourced directly by  $MSn/WSL/bash_profile

# $machBld  exported in  $OSAB/nodes-Bash/export-storage

export MANPATH=/usr/share/man/  # for  xman
export MOZ_GTK_TITLEBAR_DECORATION=client  # hide title bar and window border
export PAPERSIZE=A4  # libpaper

ur=$(uname -r)
if [[ $ur =~ 'arch' || $ur =~ 'zen' ]]; then
    export distro=Arch
    uG="$machBld/jo/Bash/exportWS"; [[ -f $uG ]] && source $uG
elif [[ $ur =~ 'microsoft' ]]; then
    export distro=WSL2
fi # $distro, used below, and in  $Cmdts1/0-adh/adherents.sh

#=> storage
# here I'm taking care to avoid variables that only differ by case

#==> code 0 $ITr
export ITr="/run/media/jo/TOSHIBA/ITr" # $ITr ($misc/ITr/ITr.md)

#==> code 0 $notDr
export notDr="$Storage/notDr"
    export cGRs="$notDr/GRs"
        export jkll="$cGRs/d-CP/d-encoding/d-Ruby/d-Jekyll"
            export mnm=$jkll/Jekyll-jekyll-minima  # $mnm  used notably in  $JHm/_layouts

#==> code 1 $GRs
[[ $distro =~ 'Arch' ]] && source $machBld/export-GRs

#==> rooting on $Drpbx
# $Drpbx  defined in
#  $MSn/WSL/bash_profile
#  $OSAB/nodes-Bash/export-storage

export DrCop="$Drpbx/Cop"
    export COT="$DrCop/OutThere" # $COT  used in  $TeNo

#===> rooting on $DJH
# $DJH  defined in
#  $MSn/WSL/bash_profile
#  $OSAB/nodes-Bash/export-storage

export cFr=$DJH/Cop-France  # $cFr  used in  $TeNo
    export CFrp=$cFr/places  # $CFrp  used in  $TeNo
export CfWk=$DJH/Cop-work
    export Cwet=$CfWk/education/technos  # $Cwet
export Cfzd=$DJH/work-Cz
    export CzMa=$Cfzd/manage  # $CzMa
    export CzPeo=$Cfzd/people
        export Cmdt=$CzPeo/adherents/dt  # Cafézoïde members data treat
            export Cmd0=$Cmdt/data-0-wgetGS  # $Cmd0
            export Cmd1=$Cmdt/data-1-adh  # $Cmd1
            export Cmdts=$Cmdt/scripts  # $Cmdts
                export Cmdts1=$Cmdts/1-process  # $Cmdts1
    export CzPhy=$Cfzd/PhysicalProperty  # $CzPhy
export DaLi=$DJH/Jo-now/DailyLife  #  $DaLi  used in  $TeNo
export ess=$DJH/Jo-now/essential
    export eFr=$ess/France  # $eFr
    export hlth=$ess/health  # $hlth
    export Sig=$ess/signatures  # $Sig  for use in creating documents
export FrFa=$DJH/Jo-F+F
    export FFIdF=$FrFa/France/IdF  # $FFIdF  used in  $TeNo
export hmlA=$DJH/hmlArch  # huge machine log Arch  $hmlA
export JCop=$DJH/Cop  # used in  $TeNo
    export JChu=$JCop/human  # used in  $TeNo
        export JCin=$JChu/ingest  # $JCin  used in  $TeNo
    export jcOT=$JCop/OutThere  # $jcOT  used in  $TeNo
    export Pr0=$JCop/Practical0
        export Pr0t=$Pr0/technos  # $Pr0t
export JHt=$DJH/Jo-technos
    export jtIT=$JHt/IT  # used in  $core  &  $jtIT
        export jtCP=$jtIT/CP  # $jtCP
        export jtUL=$jtIT/UnixLike  # $jtUL  used in  $core  &  $jtIT
            export jtULl=$jtUL/linux  # $jtULl  used in  $core  &  $jtIT
                export jtULlA=$jtULl/Arch  # $jtULlA  used in  $core  &  $jtIT
    export tIs=$JHt/IT-storage  # $tIs/diskUsage.txt
export JHThb=$DJH/Thb  # $JHThb
export JHw=$DJH/work
    export atone="$JHw/WB-Hugo/atiavda_one" # $atone
    export bilan=$JHw/ST/LPD/IdF/AB-TAP/bilan
    export JHm="$JHw/IT-Jekyll-harriott-minima" # $JHm
    export wP=$JHw/France/IdF/Paris
        export rEr=$wP/20e-rueErmitage
              export StEr=$rEr/StudioErmitage  # $StEr
export JJt0=$DJH/Jo-then0
    export T0Fr=$JJt0/world-Europe/France
        export T0Frl=$T0Fr/lieux  # $T0Frl
export TeNo=$core/TextNotes  # used in  $TeNo
    export TNt=$TeNo/tex  # *.tex's - used in  $AjB/bashrc-wm

#====> rooting on $coreIT
# $coreIT  defined in
#  $MSn/WSL/bash_profile
#  $OSAB/nodes-Bash/export-storage

export cITcc=$coreIT/copied-code  # $cITcc  - needed resources
export cITCP=$coreIT/CP
    export CPdoc=$cITCP/documenting
        export LTXj=$CPdoc/LaTeX/jo  # $LTXj
    # export CPenc=$cITCP/encoding
export cITcr=$coreIT/copied-reference  # handy
export DWp=$coreIT/DokuWiki/pages  # $DWp

#=====> rooting on $onGH
# $onHG  defined in
#  $MSn/WSL/bash_profile
#  $OSAB/nodes-Bash/export-storage

export MD4PDF=$onGH/pandoc-md4pdf  # $MD4PDF  is unambiguous
export misc=$onGH/misc  # $misc
export MSWin10=$onGH/OS-MSWin10  # $MSWin10  used in  $DWp  &  $TeNo
  export MSn=$MSWin10/nodes  # $MSn
export OSAT=$onGH/OS-Android-Termux  # $OSAT
export vimfiles=$onGH/vimfiles
    [ -d "$onGH" ] || export vimfiles=~/vimfiles  # when building Arch
    export vfn="$vimfiles/nvim"  # $vfn
    export vfv="$vimfiles/vim"
        export vfvp="$vfv/packs"  # $vfvp

#=====> rooting on $culL
# $culL  defined in
#  $MSn/WSL/bash_profile
#  $OSAB/nodes-Bash/export-storage

export lclm=$culL/clm  # $lclm  linux command-line mail

#==> rooting on $HOME
export lazy="$HOME/.local/share/nvim/lazy"  # $lazy - neovim  plugins
export nvmp="$HOME/.local/share/nvim/mason/packages"  # $nvmp
export nvim="$HOME/.config/nvim"  # $nvim

#==> rooting on $OSAB
export Imagey=$AjB/Imagey  # $Imagey  used in  $AjB/bashrc-wm
export Openbox=$ABjo/wm/Openbox
    export Obc=$Openbox/openbox  # $Obc - configurations

