#!/bin/sh
# vim: fdl=2 ft=sh:

# $OSL/nodes/jo/export

#  $OSL  defined in
#   $MSn/WSL/bash_profile
#   $OSAB/nodes-Bash/export-Arch

#  sourced by
#   $AjB/bash_profile
#   $MSn/WSL/bash_profile
#   $OSAB/nodes-root/bash_profile

# $machBld  exported in  $OSAB/nodes-Bash/export-Arch

export MANPATH=/usr/share/man/  # for  xman
export MOZ_GTK_TITLEBAR_DECORATION=client  # hide title bar and window border
export PAPERSIZE=A4  # libpaper

ur=$(uname -r)
if [[ $ur =~ 'arch' || $ur =~ 'zen' ]]; then
    export distro=Arch
    uG="$machBld/jo/Bash/exportWS"; [[ -f $uG ]] && source $uG
elif [[ $ur =~ 'microsoft' ]]; then
    export distro=WSL2
fi # $distro, used below, and in  $Cmdts1/0-adh/adherents.sh

#=> storage
# here I'm taking care to avoid variables that only differ by case

#==> code 0 $ITr
export ITr="/run/media/jo/TOSHIBA/ITr" # $ITr ($ITcore/reference/ITr.md)

#==> code 0 $notDr
export notDr="$Storage/notDr"
    export cGRs="$notDr/GRs"
        export jkll="$cGRs/d-CP/d-encoding/d-Ruby/d-Jekyll"
            export mnm=$jkll/Jekyll-jekyll-minima  # $mnm  used notably in  $Jhm/_layouts

#==> code 1 $GRs
[[ $distro =~ 'Arch' ]] && source $machBld/export-GRs

#==> rooting on  $Drpbx
# $Drpbx  defined in
#  $MSn/WSL/bash_profile
#  $OSAB/nodes-Bash/export-Arch

export ITcop=$Drpbx/IT/copied  # $ITcop - needed resources
export ITmore=$Drpbx/IT/more
    export ITmCP=$ITmore/CP  # $ITmCP
    export ITmUL=$ITmore/UnixLike
        export ITmULl=$ITmore/UnixLike/linux
            export ITmULlA=$ITmore/UnixLike/linux/Arch
export ITsto=$Drpbx/IT/storage  # $ITsto/diskUsage.txt
export DrThb=$Drpbx/Thb  # $DrThb
export ulLAhml="$Drpbx/dev/ulLA-hml"  # unix-like Linux Arch huge machine log  $ulLAhml
export ITculLAh="$Drpbx/IT-culLAh"  # IT core unix-like Linux Arch huge  $ITculLAh

#===> rooting on  $DrJo
# $DrJo  defined in
#  $MSn/WSL/bash_profile
#  $OSAB/nodes-Bash/export-Arch

export Cfzd=$DrJo/work-Cz
    export CzMa=$Cfzd/manage
        export CzMaEx=$CzMa/expenses  # $CzMaEx
    export CzPeo=$Cfzd/people
        export Cmdt="$CzPeo/members/data/dt" # Cafézoïde members data treat
            export Cmd0=$Cmdt/data-0-wgetGS  # $Cmd0
            export Cmd1=$Cmdt/data-1-adh  # $Cmd1
            export Cmdts=$Cmdt/scripts  # $Cmdts
                export Cmdts1=$Cmdts/1-process  # $Cmdts1
    export CzPhy=$Cfzd/PhysicalProperty  # $CzPhy
export ess=$DrJo/now/essential
    export eFr=$ess/France  # $eFr
    export hlth=$ess/health  # $hlth
    export Sig=$ess/signatures  # $Sig  for use in creating documents
export FrFa="$DrJo/F+F"
    export FFIdF=$FrFa/France/IdF  # $FFIdF
export Jotech=$DrJo/technos  # $Jotech
export Jwk=$DrJo/work
    export atone="$ITcore/WB-Hugo/atiavda_one" # $atone
    export bilan=$Jwk/ST/LPD/IdF/AB-TAP/bilan
    export Jhm="$ITcore/serve/Jekyll/harriott-minima" # $Jhm
    export wP=$Jwk/France/IdF/Paris
        export rEr=$wP/20e-rueErmitage
              export StEr=$rEr/StudioErmitage  # $StEr
export JJt0=$DrJo/then0
    export DaLi=$JJt0/DailyLife  #  $DaLi
    export T0Fr=$JJt0/world/Europe/France
        export T0Frl=$T0Fr/lieux  # $T0Frl
export TeNo=$DrJo/now/TextNotes
    export TNt=$TeNo/tex  # *.tex's - used in  $AjB/bashrc-wm
export ZNc="$DrJo/work-Cz-manage-online-ZNc"

#===> rooting on  $ITcore
# $ITcore  defined in
#  $MSn/WSL/bash_profile
#  $OSAB/nodes-Bash/export-Arch
#  $OSAT/bash_profile

export cITcc=$ITcore/copied-code  # $cITcc - to deprecate
export cITCP=$ITcore/CP
    export CPdoc=$cITCP/documenting
        export LTXj=$CPdoc/LaTeX/jo  # $LTXj
    # export CPenc=$cITCP/encoding
export ITref=$Drpbx/IT/reference  # $ITref
export DWp=$ITcore/serve/DokuWiki/pages  # $DWp

#====> rooting on $onGH
# $onHG  defined in
#  $MSn/WSL/bash_profile
#  $OSAB/nodes-Bash/export-storage

export MD4PDF=$onGH/pandoc-md4pdf  # $MD4PDF  is unambiguous
export misc=$onGH/misc  # $misc
export MSWin10=$onGH/OS-MSWin10  # $MSWin10
  export MSn=$MSWin10/nodes  # $MSn
export OSAT=$onGH/OS-Android-Termux  # $OSAT
export vimfiles=$onGH/vimfiles
    [ -d "$onGH" ] || export vimfiles=~/vimfiles  # when building Arch
    export vfn="$vimfiles/nvim"  # $vfn
    export vfv="$vimfiles/vim"
        export vfvp="$vfv/packs"  # $vfvp

#====> rooting on $culL
# $culL  defined in
#  $MSn/WSL/bash_profile
#  $OSAB/nodes-Bash/export-storage

export lclm=$culL/clm  # $lclm  linux command-line mail

#===> rooting on  copied
export cOT="$Drpbx/copied/OutThere" # $cOT
export cnFr="$Drpbx/copied/near-France"
    export cFrp=$cnFr/places  # $cFrp
export cnear="$Drpbx/copied/near"
    export cnhu="$cnear/human"
        export cnhi=$cnhu/ingest  # $cnhi
    export cnOT=$cnear/OutThere  # $cnOT
    export Pr0=$cnear/Practical0
        export Pr0t=$Pr0/technos  # $Pr0t
export cnwork="$Drpbx/copied/near-work"
    export cnwt=$cnwork/technos  # $cnwt
    export cnwet=$cnwork/education/technos  # $cnwet

#==> rooting on  $HOME
export lazy="$HOME/.local/share/nvim/lazy"  # $lazy - neovim  plugins
export nvmp="$HOME/.local/share/nvim/mason/packages"  # $nvmp
export nvim="$HOME/.config/nvim"  # $nvim

#==> rooting on  $OSAB
export Imagey=$AjB/Imagey  # $Imagey  used in  $AjB/bashrc-wm
export Openbox=$ABjo/wm/Openbox
    export Obc=$Openbox/openbox  # $Obc - configurations

